spring.main.banner-mode=off
spring.main.web-application-type=none
pqm.doors.projectArea=Test Template
pqm.doors.childTestPlan=FAT0X AUTO PDA All
pqm.doors.report-version=3.3.5
pqm.doors.systemDomain=https://clmstage2.werum.com:443/
pqm.doors.globalConfig=https://clmstage2.werum.com:443/gc/configuration/688
pqm.doors.user=SrvDoorsAutomation
pqm.doors.password=i2RRn4fnb6WBW1
