apiVersion: v1
kind: ConfigMap
metadata:
  name: test-data-cm
  namespace: fat
data:
  insert_test_data.sql: |
    DO $$
    DECLARE
    BEGIN

        -- Setup PASX-API accessright
      INSERT INTO pasx.authorisationprofile (
          entitykey, jcoffeeoptimisticconcurrency, "version", isglobal, profilekey
      ) VALUES (5000423687, 1, 1, 0, 'USER:101');

      INSERT INTO pasx.accessright (
          entitykey, jcoffeeoptimisticconcurrency, "version", grantdetails, isgranted,
          protectionkey, authorisationprofileentitykey
      ) VALUES (5000423688, 0, 1, NULL, 1, 'PasxApi', 5000423687);

      COMMIT;

    END $$;
